@function_tool
def excuse_quality_tool(message: str) -> str:
    """
    Tool function that evaluates the quality and appropriateness of an apology
    or explanation message generated by the Excuse Bot.

    Args:
        message: The apology or explanation message to evaluate.

    Returns:
        A formatted string containing feedback about the message quality.
    """

    message_lower = message.lower()

    feedback = []
    score = 0

    # Check politeness
    polite_words = ["sorry", "apologize", "apologies", "thank you", "appreciate"]
    if any(word in message_lower for word in polite_words):
        feedback.append("Politeness: Message contains polite language.")
        score += 1
    else:
        feedback.append("Politeness: Consider adding an apology or polite phrase.")

    # Check clarity
    if len(message.split()) > 10:
        feedback.append("Clarity: Message provides some explanation.")
        score += 1
    else:
        feedback.append("Clarity: Message may be too short to explain the situation.")

    # Check responsibility
    responsibility_words = ["i was", "i couldn't", "i missed", "i was unable"]
    if any(word in message_lower for word in responsibility_words):
        feedback.append("Responsibility: Message acknowledges the situation.")
        score += 1
    else:
        feedback.append("Responsibility: Consider acknowledging responsibility.")

    # Guardrail: detect extreme deception
    risky_phrases = ["family member died", "serious accident", "hospital emergency"]
    if any(word in message_lower for word in risky_phrases):
        feedback.append(
            "Guardrail Warning: Message may contain a serious claim that should not be fabricated."
        )

    # Final score
    quality = f"Message Quality Score: {score}/3"

    return quality + "\n\nEvaluation:\n" + "\n".join(feedback)